version: '3'

services:
  app:
    build: .
    image: golang-todo-app
    container_name: golang-todo-app
    tty: true # コンテナの永続化
    ports: # ホストOSのポートとコンテナのポートをつなげる 
      - "8080:8080"
    volumes:
      - .:/go/src/golang_todo_app # マウントディレクトリ
